# Uncomment this line to define a global platform for your project
inhibit_all_warnings!
source 'https://github.com/CocoaPods/Specs.git'
target 'WYPhotoBrowse' do
pod 'SDWebImage'
xcodeproj 'WYPhotoBrowse'
end
